chat_group/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls")),
    path("register/", home_views.register, name="register"),
    path(
        "", auth_views.LoginView.as_view(template_name="home/login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="home/logout.html"),
        name="logout",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.home, name="home"),
    path("<slug:grp_name>", views.group, name="group"),
    path("profile/<str:email>", views.profile, name="profile"),
    path("group_profile/<slug:grp_name>", views.group_profile, name="group_profile"),
    path("search_user/", views.search_user, name="search_user"),
    path("<slug:grp_name>/add_members", views.add_member, name="add_members"),
]

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Group, GroupProfile, Messages, User
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit
from crispy_forms.layout import Field


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["email"]


class ProfileUpdateForm(forms.ModelForm):

    user_info = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Profile
        fields = ["user_info", "image"]


class GroupUpdateForm(forms.ModelForm):

    group_info = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Group
        fields = ["group_name", "group_info"]


class GroupCreateForm(forms.ModelForm):

    group_info = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):

        super(GroupCreateForm, self).__init__(*args, **kwargs)

        self.fields["group_name"].label = "Group Name :"
        self.fields["group_info"].label = "Group Info :"
        self.fields["group_name"].widget.attrs["placeholder"] = "Enter Group Name..."
        self.fields["group_info"].widget.attrs["placeholder"] = "Enter Group Info..."

        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal form-class"
        self.helper.label_class = "form-group col-lg-2"
        self.helper.field_class = "input-class col-lg-10"
        self.helper.layout = Layout(
            "group_name", "group_info", Submit("submit", "Create", css_class="col-lg-2")
        )

    class Meta:
        model = Group
        fields = ["group_name", "group_info"]


class GroupProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = GroupProfile
        fields = ["image"]


class GroupProfileCreateForm(forms.ModelForm):
    class Meta:
        model = GroupProfile
        fields = ["image"]


class MessageCreateForm(forms.ModelForm):
    message_text = forms.CharField()

    class Meta:
        model = Messages
        fields = ["message_text"]


class SearchUserForm(forms.Form):

    email = forms.CharField(max_length=150, label="email", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].label = "email:"
        self.fields["email"].widget.attrs[
            "placeholder"
        ] = "Search User Name Here..."


class AddMemberForm(forms.Form):
    users = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, label="Select users to add : "
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-class"
        self.helper.field_class = "form-field-class"
        self.helper.layout = Layout(
            "users", Submit("submit", "Add To Group", css_class="col-lg-2")
        )

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Group, Messages, User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from .forms import (
    UserRegisterForm,
    UserUpdateForm,
    ProfileUpdateForm,
    GroupUpdateForm,
    GroupProfileUpdateForm,
    MessageCreateForm,
    GroupCreateForm,
    GroupProfileCreateForm,
    SearchUserForm,
    AddMemberForm
)
from django.contrib.auth.decorators import login_required
from django.http import Http404
import json
from django.utils.safestring import mark_safe

# Create your views here.


@login_required
def home(request):
    groups = request.user.all_groups.all()
    if request.method == "POST":
        g_form = GroupCreateForm(request.POST)

        if g_form.is_valid():
            group = g_form.save(commit=False)
            group.creater = request.user
            group.save()
            group.members.add(request.user)
            return redirect("home:group_profile", grp_name=group.group_name)
    else:
        g_form = GroupCreateForm()

    context = {
        "groups": groups,
        "g_form": g_form
    }
    return render(request, "home/home.html", context)


# class GroupCreateView(LoginRequiredMixin, CreateView):

#     template_name = "home/home.html"
#     fields = ['group_name' , 'group_info']

#     def get_queryset(self):
#         return self.request.user.all_groups.all()

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["groups"] = self.request.user.all_groups.all()
#         return context

    
    


# @login_required
# def group(request, grp_name):
#     group = get_object_or_404(Group, group_name=grp_name)
#     # To check wether user is member of group or not
#     try:
#         request.user.all_groups.get(group_name=grp_name)
#         # above line will throw exception if user is not permitted for the view
#         msgs = Messages.objects.filter(parent_group=group).all()
#         context = {"msgs": msgs, "group_name": grp_name}
#         return render(request, "home/group.html", context)

#     except Group.DoesNotExist:
#         raise Http404("Group Does not exist")


# class MessageCreateView(LoginRequiredMixin, CreateView):
    
#     # queryset = Messages.objects.filter(group_name=grp_name)
#     form_class = MessageCreateForm
#     model = Messages
#     template_name = 'home/group.html'


#     def dispatch(self, request, *args, **kwargs):
#         self.grp_name = kwargs['grp_name']
#         return super().dispatch(request, *args, **kwargs)

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         grp = Group.objects.get(group_name=self.grp_name)
#         context["msgs"] = reversed(grp.messages.order_by('date_posted')[:50])
#         context["group_name"] = self.grp_name
#         return context

#     def form_valid(self, form):
#         form.instance.parent_group = Group.objects.get(group_name=self.grp_name)
#         form.instance.parent_user = self.request.user
#         return super().form_valid(form)
    
@login_required
def group(request, grp_name):

    try:
        group = request.user.all_groups.get(group_name=grp_name)
    except Group.DoesNotExist:
        raise Http404("Group Does not exist or You are not member of this group")

    return render(request, 'home/group.html', {
        'room_name_json': mark_safe(json.dumps(grp_name)),
        'group' : group
        })

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")

    else:
        form = UserRegisterForm()

    return render(request, "home/register.html", {"form": form})


@login_required
def profile(request, email):

    # This will allow us to show updation form only if user is on own profile
    if request.user.email == email:
        if request.method == "POST":
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = ProfileUpdateForm(
                request.POST, request.FILES, instance=request.user.profile
            )

            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                return redirect("home:profile", email=email)

        else:
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {"required_user": request.user, "u_form": u_form, "p_form": p_form}

    else:
        required_user = get_object_or_404(User, email=email)
        context = {"required_user": required_user}

    return render(request, "home/profile.html", context)


@login_required
def group_profile(request, grp_name):
    try:
        group = request.user.all_groups.get(group_name=grp_name)
        # above line will throw exception if user is not permitted for the view
        members = group.members.all()

        if request.user.email == group.creater.email:
            if request.method == "POST":
                g_form = GroupUpdateForm(request.POST, instance=group)
                gp_form = GroupProfileUpdateForm(
                    request.POST, request.FILES, instance=group.group_profile
                )

                if g_form.is_valid() and gp_form.is_valid():
                    g_form.save()
                    gp_form.save()

                    return redirect("home:group_profile", grp_name=group.group_name)

            else:
                g_form = GroupUpdateForm(instance=group)
                gp_form = GroupProfileUpdateForm(instance=group.group_profile)

            context = {
                "members": members,
                "group": group,
                "g_form": g_form,
                "gp_form": gp_form,
            }

        else:
            context = {"members": members, "group": group}

        return render(request, "home/group_profile.html", context)

    except Group.DoesNotExist:
        raise Http404("Group Does not exist")

@login_required
def search_user(request):
    if request.method == 'POST':
        form = SearchUserForm(request.POST)

        if form.is_valid():
            users = User.objects.filter(email__startswith=form.cleaned_data.get("email"))

            context = {
                "users" : users,
                "form" : form
            }
            return render(request, "home/search_user.html", context)
    else:
        form = SearchUserForm()
        context = {
            "form" : form
        }

    return render(request, "home/search_user.html", context)



@login_required
def add_member(request, grp_name):
    
    

    try:
        global group
        group = Group.objects.get(group_name=grp_name)
        flag = group.members.get(email=request.user.email)
    except Group.DoesNotExist:
        raise Http404("Group Does not exist")



    if  flag:
        print(group.group_profile.image.url)
        if request.method == 'POST':
            if 'email' in request.POST and 'users' not in request.POST:

                form = SearchUserForm(request.POST)
                userlistform = AddMemberForm()

                if form.is_valid():
                    global users_for_choices # To access it accross if statements
                    users_for_choices = [ (user.id, user.email) for user in User.objects.filter(email__startswith=form.cleaned_data.get("email"))]
                    userlistform.fields['users'].choices = users_for_choices
                    form = SearchUserForm()
                    context = {
                        "group" : group,
                        "form" : form
                    }
                    if len(users_for_choices) > 0:
                        context["list"] = userlistform
                    print(users_for_choices)
                    return render(request, "home/add_members.html", context)
            
            # else:
            if 'users' in request.POST:
                userlist = AddMemberForm(request.POST)
                userlist.fields['users'].choices = users_for_choices

                if userlist.is_valid():
                    users = userlist.cleaned_data.get('users')
                    for user in users:
                        group.members.add(User.objects.get(id=user[0]))

                    return redirect('home:group', grp_name=grp_name)


                else:
                    print(userlist.errors.as_text())
                    form = SearchUserForm()
                    context = {
                        "form" : form,
                        "group" : group
                    }
                    
                    

            

        else:
            form = SearchUserForm()
            context = {
                "form" : form,
                "group" : group
            }
            

        return render(request, "home/add_members.html", context)

home/templates/home/group.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>GroupChat</title>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
    <script src="https://use.typekit.net/hoy3lrg.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
  </head>

<body>
  <div id="frame">
    <div id="sidepanel">
      <div id="profile">
        <div class="wrap">
          <img id="profile-img" src="{{ user.profile.image.url }}" class="online" alt="" />
          <a href="{% url 'home:profile' user %}"><p>{{ user.email }}</p></a>
          <i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>
          <div id="status-options">
            <ul>
              <li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>
              <li id="status-away"><span class="status-circle"></span> <p>Away</p></li>
              <li id="status-busy"><span class="status-circle"></span> <p>Busy</p></li>
              <li id="status-offline"><span class="status-circle"></span> <p>Offline</p></li>
            </ul>
          </div>
          <div id="expanded">
            <div class="row">
              <a class="btn btn-outline-light col-lg-5" style="margin-left:20px;font-weight:bold;padding-left:25px;"  href="{% url 'home:search_user' %}">Search Users</a>
            </div>
            <div class="row">
              <a class="btn btn-outline-light col-lg-4" style="margin-left:20px; font-weight:bold;" href="{% url 'home:home'%}">Home</a>
            </div>
            <div class="row">
              <a class="btn btn-outline-danger col-lg-4" style="font-weight:bold;margin-left:20px;" href="{% url 'logout' %}">Logout</a>
            </div>
          </div>
        </div>
      </div>
      <div id="contacts">
        <ul id="groups">
          {% comment %} <li class="contact">
            <div class="wrap">
              <span class="contact-status online"></span>
              <img src="http://emilcarlsson.se/assets/louislitt.png" alt="" />
              <div class="meta">
                <p class="name">Louis Litt</p>
                <p class="preview">You just got LITT up, Mike.</p>
              </div>
            </div>
          </li>
          <li class="contact active">
            <div class="wrap">
              <span class="contact-status busy"></span>
              <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
              <div class="meta">
                <p class="name">Harvey Specter</p>
                <p class="preview">Wrong. You take the gun, or you pull out a bigger one. Or, you call their bluff. Or, you do any one of a hundred and forty six other things.</p>
              </div>
            </div>
          </li> {% endcomment %}
        </ul>
      </div>
      <div id="bottom-bar">
        <a href='{% url 'home:add_members' group %}' style="text-decoration:none;"><button id="addcontact" class="collapse-button"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Add Members</span></button></a>
        {% comment %} <button id="settings"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></button> {% endcomment %}
      </div>
    </div>
    

    
    <div class="content">
      <div class="contact-profile">
        <img src="{{ group.group_profile.image.url }}" alt="" />
        <a href="{% url 'home:group_profile' group %}"><p>{{ group.group_name }}</p></a>
        <div id = "older_msg_div">
          <button id="check_older_messages">see older messages</button>
        </div>
        
      </div>
      <div class="messages">
        <ul id="chat-log">
          {% comment %} <li class="sent">
            <img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
            <p>How the hell am I supposed to get a jury to believe you when I am not even sure that I do?!</p>
          </li>
          <li class="replies">
            <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
            <p>When you're backed against the wall, break the god damn thing down.</p>
          </li> {% endcomment %}
        </ul>
      </div>
      <div class="message-input">
        <div class="wrap">
        <input id="chat-message-input" type="text" placeholder="Write your message..." />
        <i class="fa fa-paperclip attachment" aria-hidden="true"></i>
        <button id="chat-message-submit" class="submit">
          <i class="fa fa-paper-plane" aria-hidden="true"></i>
        </button>
        </div>
      </div>
    </div>
  </div>

<script type="text/javascript" src="{% static 'home/javascript/main.js' %}"></script>
<script type="text/javascript" src="{% static 'home/javascript/reconnecting-websocket.js' %}"></script>
<script>
    var roomName = {{ room_name_json }};
    var email = "{{ user.email }}";
    var old_msg_page_count = 0;
    var loc = window.location, new_uri;
    if (loc.protocol === "https:") {
        new_uri = "wss://";
    } else {
        new_uri = "ws://";
    }

    var chatSocket = new ReconnectingWebSocket(
        new_uri + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onopen = function(e) {
      fetchGroups();
      fetchMessages(true);
    }

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        if (data['command'] === 'messages') {

          var ChatLog = document.querySelector('#chat-log');
          var elements = ChatLog.getElementsByTagName('li');
          while(elements[0]){
            elements[0].parentNode.removeChild(elements[0]);
          }

          for (let i=0; i<data['messages'].length; i++) {
            createMessage(data['messages'][i]);
          }
          if(old_msg_page_count == 0){
            scroll();
          }

        } else if (data['command'] === 'new_message'){
          if(old_msg_page_count != 0){
            old_msg_page_count = 0;
            fetchMessages(true);
          }
          createMessage(data['message']);
          scroll();
        }
        else if (data['command'] === 'groups'){
           for (let i=0; i<data['groups'].length; i++) {
            createGroup(data['groups'][i]);
          }
        }
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#check_older_messages').onclick = function(e) {
      old_msg_page_count++;
       fetchMessages(false);
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.getElementById('chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': email,
            'grp_name' : roomName
        }));

        messageInputDom.value = '';
        scroll();
    };

    function fetchMessages(recent) {
      if(recent){
        chatSocket.send(JSON.stringify({'command': 'fetch_messages','grp_name' : roomName }));  
      }
      chatSocket.send(JSON.stringify({'command': 'fetch_old_messages','grp_name' : roomName }));
    }

    function fetchGroups() {
      chatSocket.send(JSON.stringify({'command': 'fetch_groups','email' : email }));
    }


    function convertToMonth(index){
      switch(index){
        case 1:
          return 'Jan'
        case 2:
          return 'Feb'
        case 3:
          return 'Mar'
        case 4:
          return 'Apr'
        case 5:
          return 'May'
        case 6:
          return 'Jun'
        case 7:
          return 'Jul'
        case 8:
          return 'Aug'
        case 9:
          return 'Sep'
        case 10:
          return 'Oct'
        case 11:
          return 'Nov'
        case 12:
          return 'Dec'
      }
    }

    function formatDate(date) {
      var hours = date.getHours();
      var minutes = date.getMinutes();
      var ampm = hours >= 12 ? 'pm' : 'am';
      hours = hours % 12;
      hours = hours ? hours : 12; // the hour '0' should be '12'
      minutes = minutes < 10 ? '0'+minutes : minutes;
      var strTime = hours + ':' + minutes + ' ' + ampm;
      //return strTime;
      return date.getDate() + " " + convertToMonth(date.getMonth()+1) + "  " + strTime;
    }

    function createGroup(data) {
      var groupName = data['group_name'];
      var aTag = document.createElement('a');
      var msgListTag = document.createElement('li');
      var wrapDivTag = document.createElement('div');
      var imgTag = document.createElement('img');
      var metaDivTag = document.createElement('div');
      var namePTag = document.createElement('p');
      var previewPTag = document.createElement('p');
      
      namePTag.textContent = data.group_name;
      previewPTag.textContent = data.last_msg;

      imgTag.src = data.profile_pic;
      aTag.href = '/home/' + groupName;
      aTag.style = "text-decoration:None;";
      if (roomName === groupName) {
        msgListTag.className = 'contact active';
      } else {
        msgListTag.className = 'contact';
      }

      
      wrapDivTag.className = 'wrap';
      metaDivTag.className = 'meta';
      namePTag.className = 'name';
      previewPTag.className = 'preview';

      aTag.appendChild(namePTag)
      msgListTag.appendChild(wrapDivTag);
      wrapDivTag.appendChild(imgTag);
      wrapDivTag.appendChild(metaDivTag);
      metaDivTag.appendChild(aTag);
      metaDivTag.appendChild(previewPTag);

      document.querySelector('#groups').appendChild(msgListTag);
    }

    function createMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('li');
      var imgTag = document.createElement('img');
      var pTag = document.createElement('p');
      var smallTag = document.createElement('small');
      var nameTag = document.createElement('small')
      var breakTag = document.createElement('br');
      var breakTag2 = document.createElement('br');
      var msgTag = document.createElement('p');
      var date_posted = new Date(data.timestamp);
      nameTag.textContent = author;
      msgTag.textContent = data.content;
      msgTag.className = "no-mp";
      
      smallTag.textContent = formatDate(date_posted);
      smallTag.className = 'time_posted';
      
      imgTag.src = data["author_profile_img"];
      
      if (author === email) {
        msgListTag.className = 'replies';
      } else {
        msgListTag.className = 'sent';
      }
      msgListTag.appendChild(imgTag);
      msgListTag.appendChild(pTag);
      pTag.appendChild(nameTag);
      pTag.appendChild(breakTag2);
      pTag.appendChild(msgTag);
      pTag.appendChild(breakTag);
      pTag.appendChild(smallTag);
      document.querySelector('#chat-log').appendChild(msgListTag);
    }

</script>
</body>

</html>

home/templates/home/group_profile.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GroupChat</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'home/css/style_profile.css' %}">
</head>
<body class="bgc">
  

 <nav class="navbar navbar-expand-sm navbar-light" style="background-color:#e9ecef;">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Group Info</a>
  
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item rounded">
      <a class="nav-link" href="{% url 'home:home' %}">Home</a>
    </li>
    {% if user in group.members.all %}
        <li class="nav-item rounded">
            <a class="nav-link" href="{% url 'home:add_members' group %}">Add Members</a>
        </li>
    {% endif %}

    {% if group.creater == user %}    
        <li class="nav-item rounded">
            <a data-toggle="collapse" id="update-prof" class="nav-link" href="#update-form">Update Group Info</a>
        </li>
    {% endif %}
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item rounded">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  
</nav>
  
<div class="jumbotron text-center">
  <h1 class="profile-heading">{{ group.group_name }}</h1>
  
    <img id="img-div" src="{{ group.group_profile.image.url }}" class="rounded-circle">
    <p class="text-secondary">Created By {{ group.creater }}</p>
    {% if group.group_info %}
        <p>{{ group.group_info }}</p>
    {% endif %}
</div>

{% if group.members %}
    <h2 class="text-center" style="color:black;">Members Of {{ group }}</h2>
{% endif %}

<div class="container">
    {% for member in members %}
        <div class="media group-box">    
            <img class="rounded-circle account-img" src="{{ member.profile.image.url }}">
            <div class="media-body">
            <h2 class="account-heading"><a href="{% url 'home:profile' member %}">{{ member.email }}</a></h2>
            {% if member.profile.user_info %}
                <p class="text-secondary preview">{{ member.profile.user_info }}</p>
            {% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
</div>
<div class="container text-white-50">
  
  
    {% if group.creater == user %}
        <div id="update-form" class="collapse">
            
            <form method="POST" enctype="multipart/form-data">
                <fieldset class="form-group">
                    {% csrf_token %}
                    <legend class="border-bottom mb-4 bcg">Profile Info</legend>
                    {{ g_form|crispy }}
                    {{ gp_form|crispy }}
                </fieldset>
                <div class="form-group" id="submit-btn-div">
                    <button class="btn btn-outline-info" type="submit">Update</button>
                </div>
            </form>
        </div>
    {% endif %}
</div>

</body>
<script>

$("#update-prof").on('click',function() {
   $('html,body').animate({scrollTop: document.body.scrollHeight},"slow");
});

</script>
</html>

home/templates/home/logout.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GroupChat</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'home/css/style_login.css' %}" />
</head>
<body class="bgc">
  
<div class="jumbotron text-center">
    <h1>You Have Been Logged Out!</h1>
    <p class="class=container text-muted">Login Again To Continue</p>
    <small class="text-muted">
        <a class="ml-2" href="{% url 'login' %}">Login Now</a>
    </small>
  
</div>
  
  

</body>
</html>